-- migrate:up

INSERT INTO specialisms (id, name) VALUES
  (1, 'CIRUJANO DENTISTA'),
  (2, 'PACIENTES ESPECIALES'),
  (4, 'PERIODONCIA'),
  (6, 'PATOLOGIA ORAL'),
  (7, 'ENDODONCIA'),
  (8, 'CIRUJANO DENTISTA/ REHABILITACIÓN ORAL'),
  (9, 'IMPLANTOLOGIA ORAL INTEGRAL'),
  (12, 'CIRUGÍA BUCAL  Y MAXILO FACIAL'),
  (13, 'ODONTOPEDIATRÍA'),
  (14, 'ORTODONCIA'),
  (16, 'CIRUGIA  BUCAL Y MAXILO FACIAL, PATOLOGIA'),
  (17, 'PERIODONCIA E IMPLANTES'),
  (21, 'ORTODONCIA E IMPLANTES'),
  (22, 'REHABILITACIÓN ORAL'),
  (28, 'IMPLANTOLOGIA'),
  (31, 'IMPLANTOLOGIA / REHABILITACION ORAL'),
  (32, 'ESTETICA DENTAL'),
  (33, 'ODONTOPEDIATRÍA / ORTODONCIA');

-- migrate:down

TRUNCATE specialisms;